### ISSUE TITLE
Add providers as a filter option on import tab

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADAShiny#129]
**Is your feature request related to a problem? Please describe.**

TADA_DataRetrieval now includes the function input providers. This filter option should be included on the data import tab.

**Comment by JamesBisese** [comment]
I think the issue is referring to data source PROVIDERS which include 'NWIS (USGS)', 'WQX (EPA)'

In WQP this UI element is shown in the Download the Data section, after the other filters.

![image](https://github.com/USEPA/TADAShiny/assets/16490554/06822d42-55db-4bc7-a415-303e682cb5c2)

**Comment by JamesBisese** [comment]
I can add this pretty easily.  I still need to do the step-by-step work to implement it.

![image](https://github.com/USEPA/TADAShiny/assets/16490554/0c9f3d34-28d1-4394-a5a8-5b2ebef270cf)

**Comment by cristinamullin** [comment]
Yes that is the correct. This ticket is referring to the data source PROVIDERS. 

The import tab links the filters to the TADA_DataRetrieval function which already includes the providers 
function input: https://usepa.github.io/TADA/reference/TADA_DataRetrieval.html

**Comment by JamesBisese** [comment]
To add the new filter I added code to mod_query_data.R

Get and prepare the filter options
```

```

Add the new UI element, hardwiring in the 2 options
```
    shiny::fluidRow(column(
      4,
      shiny::checkboxGroupInput(ns("providers"), "Data Source", c("NWIS (USGS)" = "NWIS", "WQX (EPA)" = "STORET"))
    )),
```

Add code to process argument for new UI element if selected

```
      if (is.null(input$providers)) {
        tadat$providers <- "null"
      } else {
        tadat$providers <- input$providers
      }
```

Finally, use it in the query that actually gets the data

```
      # storing the output of TADAdataRetrieval with the user's input choices as a reactive object named "raw" in the tadat list.
      raw <- TADA::TADA_DataRetrieval(
        statecode = tadat$statecode,
        countycode = tadat$countycode,
        countrycode = tadat$countryocean_value, # New filter added and simple testing. Use China 2018-05-01 2018-11-01
        huc = tadat$huc,
        siteid = tadat$siteid,
        siteType = tadat$siteType,
        characteristicName = tadat$characteristicName,
        characteristicType = tadat$characteristicType,
        sampleMedia = tadat$sampleMedia,
        project = tadat$project,
        organization = tadat$organization,
        startDate = tadat$startDate,
        endDate = tadat$endDate,
        providers = tadat$providers,
        applyautoclean = TRUE
      )
```

**Comment by JamesBisese** [comment]
Use China with date range 2018-05-01 to 2018-11-01

Set Data Source NWIS
Your query returned zero results.

Set Data Source WQX
Your dataset contains 70 unique results from 5 monitoring location(s) and 1 unique organization(s).

Do not set either (leave them blank)
Your dataset contains 70 unique results from 5 monitoring location(s) and 1 unique organization(s).

Set Data Source NWIS and WQX
Your dataset contains 70 unique results from 5 monitoring location(s) and 1 unique organization(s).

**Comment by JamesBisese** [comment]
There is a slight tweak required - changing the selection into a Radio Button.  This is needed to handle where users want to select both NWIS and WQX.
