### ISSUE TITLE
Manage button clicks and input on Censored Data tab as the method is applied or undone

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADAShiny#158]
**Describe the bug**

**If a user clicks "Apply Methods to Dataset" more than once... the method is applied over and over.** 

For example, 
Non-Detect Handling Method = Multiply detection limit by x
Multiplier (x) = 0.5
Over-Detect Handling Method = No change
**then each time the sum reduction =  ½   * ½   *  ½.** 

Also, multiple different methods can be applied now which does not make sense. A user must only select one, and then undo the method if they want to select and apply a different one after reviewing the table.

**To Reproduce**

Use any dataset and go to the censored data tab, click the "Apply Methods to Dataset" button more than once and observe.

**Expected behavior**

The "Apply Methods to Dataset" button should only be able to be clicked once. After that, the button should disappear or maybe  turn grey. If a user wants to undo the method they can click the "Undo Method Application" button. If they click that, they the "Apply Methods to Dataset" should be made available again.

**Screenshots**

![image](https://github.com/USEPA/TADAShiny/assets/46969696/2ec1223c-550c-4bcb-92a5-9cdb85f51cd0)

**Reminders for TADA contributors addressing this issue**

New features should include all of the following work:

-   [ ] Create the function/code.

-   [ ] Document all code using comments to describe what is does.

-   [ ] Create tests.

**Comment by JamesBisese** [comment]
I imagine we will need to set a session variable to prevent re-application of the filter, and to indicate to downstream processing that this element has been applied..  We also want to disable the select button after it has been applied once.

**Comment by JamesBisese** [comment]
I added an 'enable' line, but now see that once you run the apply_method the first time you also have to disable to multiplier field because if you change that and then 'undo' it uses the new value and you can't get back to where you started.

This is what I added to the shiny::observeEvent(input$undo_methods

```
      # (re)enable the button so the user can redo the handling
      shinyjs::enable("apply_methods")
      shinyjs::enable("nd_mult")
```

**Comment by JamesBisese** [comment]
This ticket will take 3-4 hours.  I need to deal with these issues
1) signaling the observable to re-enable when new data is loaded using any one of 3 paths (WQP, Upload dataset, upload Progress File)
2) Disable the 'nd_mult' and 'od_mult' fields - so it can't be changed once they have been run once.
3) Disable the 'Undo' button if there has been no Censor run.
4) Enable the Undo button after the Censor has been run

branch: Manage-input-on-Censore-tab-#158

**Comment by JamesBisese** [comment]
This took less time than I thought.  Here is the behavior now
1) if user hits the "Apply Methods to Dataset" button the other Censor buttons and UI elements are disabled
2) if the user hits the Undo Methods the UI elements are enabled.

![image](https://github.com/user-attachments/assets/f2b66e9b-d105-494c-8c91-8dc7cb2d1658)

and after hitting Apply ...

![image](https://github.com/user-attachments/assets/bcaf1564-47b3-48a0-8f26-c55f8754bc76)

Then after hitting "Undo Method Application"

![image](https://github.com/user-attachments/assets/05642bec-c092-41cb-a741-6fe0392ed722)

I ran the process repeatedly and the numbers on the example first-10-rows seems to stay the same.

**Comment by JamesBisese** [comment]
Note: need to find a dataset with Over-Detects in order to test the Over-Detect handling.  I am using Utah 15k example data and there are no over detects. Shepardstown has 1 over-detect, although there are 1809 rows flagged "Result value(s) above the national threshold for a given characteristic, possibly indicating non-sensical value(s) (see TADA.ResultValueAboveUpperThreshold.Flag)"
