### ISSUE TITLE
Disable "Apply Methods to Dataset" button on Censored Data tab if no Multiplier (x) is provided

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADAShiny#173]
**Describe the bug**

Censored Data tab will crash if no Multiplier (x) is provided (left NA) before a user hits apply.

**To Reproduce**

1. open app in R studio and load any data (I used the Nutrients UT example dataset)
2. skip to flag tab and run tests
3. skip to Censored Data tab, scroll down and remove 0.5 (default value) from Multiplier (x). Hit "Apply Methods to Dataset". The app will crash.

``` r
Error: (converted from warning) Error in if: missing value where TRUE/FALSE needed
```

**Expected behavior**

The app should not crash. Instead, a message should pop up reminding the user to populate Multiplier (x) with a value.

**Screenshots**

<img width="794" alt="image" src="https://github.com/user-attachments/assets/16a2a8d6-1882-405d-8dd6-fd9d4880ceab">

**Comment by JamesBisese** [comment]
The Apply Methods to Dataset should not be active if there is no value in the Multiplier (x) field.

I will disable the Apply Methods to Dataset button until the Multiplier (x) is entered.  This will take about 1 hour

**Comment by JamesBisese** [comment]
Updated behavior
1) Disable "Apply Methods to Dataset" if both Over and Under detect are "No Change"
1) Disable "Apply Methods to Dataset" if either Over and Under detect are "Multiple Detection Limit by X" and the associated input box is blank
1) Disable "Apply Methods to Dataset" if the Censor has been run
