### ISSUE TITLE
HTML Header

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADAShiny#41]
**Describe the bug**
For all links in the EPA header, 2 tabs open instead of 1. Also, the EPA image logo should bring you to EPA home page (https://www.epa.gov/), but it is not responsive.

**To Reproduce**
Open Shiny app and click on tabs and EPA logo within the EPA HTML header.

**Expected behavior**
The tabs and buttons should only open one tab. The EPA image logo should bring you to EPA home page (https://www.epa.gov/).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser safari

**Comment by ehinman** [comment]
Fixed before NMC.
