### ISSUE TITLE
Excel workbook upload - dates cause error

### ISSUE THREAD

**Issue by ehinman** [USEPA/TADAShiny#43]
**Describe the bug**
**Sometimes** I downloaded a dataset using the Shiny app and then tried re-uploading the dataset to the Shiny app. Because the dates were saved as number of days from origin rather than "YYYY-MM-DD", the app throws an error in the overview page on the time series bar chart. The dates need to be saved as character strings instead (I think). 

**To Reproduce**
1. Query a dataset in Shiny
2. Download the dataset
3. Re-upload dataset to Shiny
4. Navigate to overview page and look at time series

**Expected behavior**
Upload should be seamless.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cristinamullin** [comment]
Not sure if this will fix tis issue, but consider using csv input and outputs instead of xlsx

**Comment by cristinamullin** [comment]
All date and/or time fields in the data frame: 

ActivityStartDate, ActivityEndDate, AnalysisStartDate, LastUpdated, ActivityStartDateTime, ActivityEndDateTime, ConstructionDateText, ActivityStartTime.Time, ActivityEndTime.Time
