### ISSUE TITLE
Deploying desktop apps with R

### ISSUE THREAD

**Issue by ehinman** [USEPA/TADAShiny#49]
**Is your feature request related to a problem? Please describe.**
It is hard to know how many users the online shiny app can support and how much data they can pull/work with. Currently, the proto app has difficulty with two instances of the app running at the same time.

**Describe the solution you'd like**
One alternative to using online cloud services might be to create an application that users can download to run the shiny app locally. See links: 
https://stackoverflow.com/questions/15884975/possible-to-run-rshiny-app-without-opening-an-r-environment
https://www.r-bloggers.com/2014/04/deploying-desktop-apps-with-r/
https://foretodata.com/how-to-make-a-standalone-desktop-application-with-shiny-and-electron-on-windows/

**Comment by cristinamullin** [comment]
Can explore this further but having R as a basic requirement is reasonable.
