### ISSUE TITLE
TADAShiny crashes when ProjectURL column missing - PSEUDO-DEVELOP FIX

### ISSUE THREAD

**Issue by ehinman** [USEPA/TADAShiny#51]
**Describe the bug**
Sometimes, there is no QAPP URL information associated with a dataset, and that column is not included in the TADA data profile. When shiny tries to run the QAPP flags, the checkColumns function throws an error because the required columns are not present. Rather than making this fix in TADA, I think it should instead be in an if statement in the flagging tests file.

**To Reproduce**

**Expected behavior**
Shiny does not try to run tests that are not applicable to the dataset.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ehinman** [comment]
Related to: https://github.com/USEPA/TADA/issues/242, which I closed to cover on this issues section.

**Comment by cristinamullin** [comment]
@ehinman I merged in pseudo-develop, can this issue be closed now?
