### ISSUE TITLE
Remove proto link from "About" section

### ISSUE THREAD

**Issue by ehinman** [USEPA/TADAShiny#55]
**Describe the bug**
The proto URL no longer works. It should be removed from the About section of the TADAShiny Github. I'm not sure how to do it!

**Comment by cristinamullin** [comment]
I think this is already done. Do you still see it there?

**Comment by ehinman** [comment]
Nope! Looks great now, thanks.

Elise


Elise Hinman, Ph.D. (she/her)

ORISE Participant

Water Data Integration Branch

Watershed Restoration, Assessment, and Protection Division

Office of Wetlands, Oceans and Watersheds

US EPA|Office of Water

***@***.***

________________________________
