### ISSUE TITLE
Flagging table does not respond to switches properly

### ISSUE THREAD

**Issue by elisehinman** [USEPA/TADAShiny#62]
**Describe the bug**
I went through the shiny app with one dataset, and then went to the first page to try another dataset in the same session. The second dataset loaded fine into the app, and the flagging table loaded fine, but the switches no longer changed the summary removed/retained when turned on/off, and I believe was no longer affecting the tadat$removals or some other reactive object. I am wondering if this is due to the unpredictable behavior of observes within observers, which occurs in the observeEvent function in the flagging module.

**To Reproduce**
1. Load one test dataset, and run flagging functions
2. Load second test dataset, re-run flagging functions
3. Switch on an off switch with results affected and look at summary table

**Expected behavior**
The flagging table should be responsive to multiple datasets in one session.

**Comment by elisehinman** [comment]
@cristinamullin Because of this issue, please advise users to reload the shiny app when starting with a new dataset.

**Comment by cristinamullin** [comment]
No problem, thanks for the heads up

**Comment by cristinamullin** [comment]
I think it is fine to address this issue by simply adding a warning or text on the import tab to tell users that they must **reload the shiny app before starting to work with a new dataset**.
