### ISSUE TITLE
Pie Chart on Review and Explore tab

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADAShiny#65]
**Describe the bug**
Pie chart does not show up when window size is small.

**To Reproduce**
See Review and Explore tab

**Expected behavior**
Figure should include automatic text wrapping depending on window size. 

**Screenshots**
![image](https://github.com/USEPA/TADAShiny/assets/46969696/a68e2c67-61b9-4544-9cbe-efa478d16e5c)

![image](https://github.com/USEPA/TADAShiny/assets/46969696/ff93ef51-f394-42e9-9696-6fe8bc5ad963)

**Comment by ehinman** [comment]
Fixed in TADA_FieldValuesPie(). Also, there is a function called TADA_InsertBreaks() that can be used in any figure function.
