### ISSUE TITLE
Remove utils from cloud-gov r.yml

### ISSUE THREAD

**Issue by elinork** [USEPA/TADAShiny#66]
I don't want to make changes ahead of your demo, but I got a warning that I shouldn't have included utils in your r.yml file in the cloud-gov branch. This issue is just a reminder to remove it after your demo and confirm the warning goes away.

**Comment by cristinamullin** [comment]
Thanks @elinork. Feel free to make this anytime now

**Comment by elinork** [comment]
Great! It deployed without that warning, and I really doubt there would be an impact (other than me lowering the memory back to 2.8GB), but let me know if anything seems amiss now.
