### ISSUE TITLE
Filtering page - are NA's excluded from second table?

### ISSUE THREAD

**Issue by ehinman** [USEPA/TADAShiny#70]
**Describe the bug**
I was playing around with the shiny app, and I noticed when looking at the HydrologicCondition column, there was no option for rows with NA in that column. This might be something someone wants to filter out (e.g. "I only want results where column X is NOT NA"), but currently they can't see how many results are NA in that column.

**To Reproduce**
1. Upload a test dataset
2. Go to filtering tab
3. Click on a column that would likely have NAs populated
4. Review unique column options below

**Expected behavior**
A row in the second table should be blank or say "NA" to represent columns populated as NA

**Screenshots**
<img width="937" alt="image" src="https://github.com/USEPA/TADAShiny/assets/121896266/2a0e0f28-0b62-466f-9694-083ae414a4e4">
<img width="320" alt="image" src="https://github.com/USEPA/TADAShiny/assets/121896266/81b3e401-ce98-49b3-9f99-a2b1191ed66e">

Note that the total number of results in this queried dataset is ~36k, while the total number of results yielding the options in the table is only ~6k. The rest are likely NA's.

**Comment by cristinamullin** [comment]
A few people at our recent training mentioned this as well. I agree - Let's include counts for the NA's.
