### ISSUE TITLE
Update Option 3 to include "download blank TADA template" button

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADAShiny#84]
**Please describe.**
On the Load tab, under Option C: 

- Add a "download blank TADA template" button to assist users.
- Use [TADA_GetTemplate()](https://usepa.github.io/TADA/reference/TADA_GetTemplate.html). TADA_GetTemplate may need updating to meet this shiny requirement

**Comment by JamesBisese** [comment]
I got the 'Download Template' button working locally.  And found issues with TADA actually accepting the template.  Seeing the task description, I now understand that I need to work on both the template and the upload processing.  I will take that on now.

![image](https://github.com/user-attachments/assets/d0af654b-312f-4abb-a4d9-1d7d409a0006)

**Comment by JamesBisese** [comment]
The download works now.  This ticket should be closed.  And a new ticket opened that describes the errors that occur when the template is used and how to implement the upload using the template.

**Comment by cristinamullin** [comment]
@JamesBisese Great! Can you submit a pull request with these changes (addition of the new download template button which use s the [TADA_GetTemplate ](https://usepa.github.io/EPATADA/reference/TADA_GetTemplate.html)function)?

We can close this after the changes are reviewed and merged into develop.
