### ISSUE TITLE
Feedback from WDIB

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADAShiny#97]
Attaching feedback from WDIB internal review
- [TADAshiny_KevinsReview.docx](https://github.com/USEPA/TADAShiny/files/12611900/TADAshiny_KevinsReview.docx)
- [tada_comments_kiki.docx](https://github.com/USEPA/TADAShiny/files/12553410/tada_comments_kiki.docx)

**Comment by cristinamullin** [comment]
Regarding adding counts to the data retrieval, see web services documentation: https://www.waterqualitydata.us/data/swagger-ui/index.html?docExpansion=none&url=/data/v3/api-docs#/Result/resultPostCountRequest

**Comment by JamesBisese** [comment]
I think 'warning' the user about the number of results using a pop-up before loading into TADA is in line with what WQP does, and would save a huge amount of bandwidth.  This is in Kevin's comments.  Here is the WQP 'warning' pop-up.


![image](https://github.com/USEPA/TADAShiny/assets/16490554/748fc164-bb0e-408a-b0c6-4d03cfc6e781)

**Comment by cristinamullin** [comment]
I am creating separate issues for remaining tasks identified from Kiki & Kevin's review: 
https://github.com/USEPA/TADAShiny/issues/159
https://github.com/USEPA/TADAShiny/issues/158
https://github.com/USEPA/TADAShiny/issues/160

I already addressed Kevin's suggestion to switch the bar chart axis in cm-release-review-2 branch and will merge in next week. Already addressed some of Kiki's comments there as well. Remaining ones are now in the issues above.
